package com.onmobile.vol.referralchain.app.dataaccess.domain;

public enum Action {
	NO_ACTION ,
	PARENT_REGISTER,
	ADD_CHILD,
    REMOVE_CHILD,
    CHILD_REJECT,
    CHILD_EXPIRED,
    CHILD_ACCEPTED,
    CHILD_DEACTIVATED,
    PARENT_DEACTIVATED,
    STATUS_CHANGE,
    SMS_STATUS_CHANGE,
	
	 
    //PrismpecificActions
	
   
	PARENT_ACT_SUCCESS,
	PARENT_ACT_FAILURE,
	
	PARENT_DCT_SUCCESS,
	PARENT_DCT_FAILURE,
	PARENT_REN_FAILURE,
	PARENT_REN_SUCCESS,
	
	PARENT_SUS_SUCCESS,
	PARENT_SUS_FAILURE,
	
	PARENT_RES_SUCCESS,
	PARENT_RES_FAILURE,
	
	
	CHILD_ACT_SUCCESS,
	CHILD_ACT_FAILURE,
	CHILD_DCT_SUCCESS;
	
}